language: julia

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        # - julia --color=yes -e 'using Pkg; Pkg.add("Documenter")'
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip